### PR TITLE
Recursive listing of movies/shows

### LINKED ISSUE #5: [Feature Request] -  Recursive listing of movies/shows
As of now, the video files in the default setup folder are displayed for selection and playing. But there are cases where people have directories under the default setup folder, and so on. 

So, can we display not just the video in the default setup folder, but every single video under every directory under the default setup folder?

### PR DESCRIPTION
**Pull request by Vivy24**
Find videos from all subfolders inside default folder

Fix #5

### CODE REVIEW

**Comment by virajsazzala** [comment]
@Vivy24 This is really good, but can you write a few comments to your code? Would be very helpful for other contributors :)

Once that's done, I'll merge it!

**Comment by Vivy24** [comment]
@virajsazzala  Of course ! I will write some comments and update it back ASAP

**Comment by Vivy24** [comment]
@virajsazzala I added some comments, let me know if you need more

**Comment by virajsazzala** [comment]
@Vivy24 Perfect, Thanks for working on this!

**Comment by virajsazzala** [comment]
LGTM!

**Pull request merged**
